package in.jharkhand.civic.service;
import in.jharkhand.civic.repository.JsonStore; import org.springframework.stereotype.Service; import java.util.*; import java.util.stream.*;
@Service public class RoutingEngine {
 private final ReferenceService ref; private final JsonStore store; public RoutingEngine(ReferenceService r,JsonStore s){ref=r;store=s;}
 private Set<String> toks(Object x){return Arrays.stream(String.valueOf(x==null?"":x).toLowerCase().replaceAll("[^a-z0-9& ]"," ").split("\\s+" )).filter(v->v.length()>3).collect(Collectors.toSet());}
 private double overlap(Set<String>a,Set<String>b){if(a.isEmpty()||b.isEmpty())return 0;Set<String>x=new HashSet<>(a);x.retainAll(b);return (double)x.size()/Math.min(a.size(),b.size());}
 public Map<String,Object> route(Map<String,Object> p,Map<String,Object> ai){
  String text=String.valueOf(p.get("title"))+" "+p.get("description")+" "+ai.get("domain")+" "+ai.get("subDomain"); Set<String> base=toks(text); List<String> req=new ArrayList<>(); Object re=ai.get("requiredExpertise"); if(re instanceof List<?> l)l.forEach(v->req.add(String.valueOf(v))); Set<String> reqSet=toks(String.join(" ",req));
  Map<?,?> locMap=p.get("location") instanceof Map<?,?> m?m:Map.of(); String district=String.valueOf(locMap.get("district")==null?"":locMap.get("district")); String priority=String.valueOf(ai.getOrDefault("recommendedPriority","MEDIUM")); double priorityBoost=switch(priority){case "CRITICAL"->1.0;case "HIGH"->0.85;case "LOW"->0.35;default->0.6;};
  List<Map<String,Object>> ds=new ArrayList<>(); for(Map<String,Object>d:ref.departments()){Set<String> ex=toks(d.get("name")+" "+d.get("category")+" "+d.get("responsibilities")+" "+d.get("expertise")); double exScore=overlap(base,ex); double aiScore=overlap(reqSet,ex); double score=.55*exScore+.30*aiScore+.10*priorityBoost+.05; List<String> reasons=new ArrayList<>(); if(exScore>.05)reasons.add("Problem language matches department responsibilities"); if(aiScore>.05)reasons.add("Required expertise aligns with department scope"); if(priorityBoost>.7)reasons.add("Priority increases urgency suitability"); if(reasons.isEmpty())reasons.add("Broad sector compatibility based on source responsibilities"); ds.add(Map.of("departmentId",d.get("id"),"name",d.get("name"),"score",round(Math.min(1,score)),"matchingReasons",reasons));}
  ds.sort((a,b)->Double.compare(((Number)b.get("score")).doubleValue(),((Number)a.get("score")).doubleValue()));
  List<Map<String,Object>> ins=new ArrayList<>(); for(Map<String,Object>i:ref.institutions()){Set<String> ex=toks(i.get("expertise")); double exp=overlap(reqSet,ex); double textScore=overlap(base,ex); double loc=district.equalsIgnoreCase(String.valueOf(i.get("district")))?1:0; int tier=((Number)i.getOrDefault("tier",4)).intValue(); double tierBonus=switch(tier){case 1->.10;case 2->.08;case 3->.06;default->.04;}; double capacity=switch(String.valueOf(i.getOrDefault("capacity","MEDIUM"))){case "HIGH"->1.0;case "LOW"->0.45;default->0.75;}; double score=.50*exp+.20*textScore+.12*loc+.08*capacity+.05*priorityBoost+.05*tierBonus; List<String> reasons=new ArrayList<>(); if(exp>.05)reasons.add("Required expertise matches published capability"); if(textScore>.05)reasons.add("Problem terms align with published expertise"); if(loc>0)reasons.add("Relevant district/location match"); reasons.add("Capacity contributes to suitability"); reasons.add("Tier contributes a limited matching bonus; it does not dominate expertise"); ins.add(Map.of("institutionId",i.get("id"),"name",i.get("name"),"tier",i.get("tier"),"score",round(Math.min(1,score)),"matchingReasons",reasons));}
  ins.sort((a,b)->Double.compare(((Number)b.get("score")).doubleValue(),((Number)a.get("score")).doubleValue())); return Map.of("departments",ds.stream().limit(5).toList(),"institutions",ins.stream().limit(8).toList(),"industryInvolved",false,"generatedAt",java.time.Instant.now().toString());
 } private double round(double x){return Math.round(x*100.0)/100.0;}
}
