package in.jharkhand.civic.service;
import in.jharkhand.civic.repository.JsonStore; import org.springframework.stereotype.Service; import java.time.Instant; import java.util.*;
@Service public class WorkflowService {private final JsonStore s;private final IdService ids;private final AuditService audit; private final JsonNotificationService notifications; public WorkflowService(JsonStore s,IdService i,AuditService a,JsonNotificationService n){this.s=s;this.ids=i;this.audit=a;this.notifications=n;}
 public Map<String,Object> createProject(String actor,Map<String,Object> req){String problemId=String.valueOf(req.getOrDefault("problemId",""));if(problemId.isBlank())throw new RuntimeException("problemId is required");Map<String,Object> problem=s.find("problems.json",problemId);if(problem==null)throw new RuntimeException("Problem not found");if(!Set.of("ACCEPTED","ROUTED","COLLABORATION_OPEN").contains(String.valueOf(problem.get("status"))))throw new RuntimeException("Problem must be routed and accepted before project creation");Map<String,Object> p=new LinkedHashMap<>(req);p.putIfAbsent("id",ids.id("project"));p.put("projectId",p.get("id"));p.putIfAbsent("industryPartnerIds",List.of());p.putIfAbsent("milestones",List.of());p.putIfAbsent("status","COLLABORATION_OPEN");p.putIfAbsent("expectedImpact",Map.of());p.putIfAbsent("actualImpact",Map.of());p.put("createdAt",Instant.now().toString());s.add("projects.json",p); String[] stages={"Research","Requirement Analysis","Design","Prototype","Internal Testing","Field Testing","Validation","Deployment","Impact Measurement"}; int idx=0; for(String stage:stages){Map<String,Object> m=new LinkedHashMap<>();m.put("id",ids.id("milestone"));m.put("projectId",p.get("id"));m.put("name",stage);m.put("description","Lifecycle milestone: "+stage);m.put("startDate","");m.put("endDate","");m.put("status",idx==0?"IN_PROGRESS":"NOT_STARTED");m.put("progress",idx==0?5:0);s.add("milestones.json",m);idx++;} audit.log(actor,"DEPARTMENT","PROJECT_CREATED","PROJECT",String.valueOf(p.get("id")),null,p); String uid=String.valueOf(p.getOrDefault("userId","")); if(!uid.isBlank()) notifications.notifyUser(uid,"Project created","Your civic problem has entered the project collaboration stage."); return p;}
 public java.nio.file.Path dataDir(){return s.dataDir();}
 public List<Map<String,Object>> projects(){return s.read("projects.json");}public Map<String,Object> project(String id){return Optional.ofNullable(s.find("projects.json",id)).orElseThrow();}public Map<String,Object> updateProject(String id,Map<String,Object> patch){patch.put("updatedAt",Instant.now().toString());return Optional.ofNullable(s.update("projects.json",id,patch)).orElseThrow();}
 public List<Map<String,Object>> milestones(String pid){return s.read("milestones.json").stream().filter(x->pid.equals(String.valueOf(x.get("projectId")))).toList();}public Map<String,Object> addMilestone(String actor,String pid,Map<String,Object> req){Map<String,Object> m=new LinkedHashMap<>(req);m.put("id",ids.id("milestone"));m.put("projectId",pid);m.putIfAbsent("status","NOT_STARTED");m.putIfAbsent("progress",0);s.add("milestones.json",m);audit.log(actor,"INSTITUTION","MILESTONE_CREATED","MILESTONE",String.valueOf(m.get("id")),null,m);return m;}public Map<String,Object> updateMilestone(String actor,String id,Map<String,Object> patch){Map<String,Object> m=s.update("milestones.json",id,patch);if(m==null)throw new RuntimeException("Milestone not found");return m;}
 public Map<String,Object> updateCollaboration(String id,Map<String,Object> patch){Map<String,Object> x=s.update("collaborations.json",id,patch);if(x==null)throw new RuntimeException("Collaboration not found");return x;}
 public Map<String,Object> collaboration(String actor,String pid,Map<String,Object> req){Map<String,Object> c=new LinkedHashMap<>(req);c.put("id",ids.id("collab"));c.put("projectId",pid);c.putIfAbsent("status","DRAFT");s.add("collaborations.json",c);audit.log(actor,"INDUSTRY","COLLABORATION_CREATED","COLLABORATION",String.valueOf(c.get("id")),null,c);return c;}public List<Map<String,Object>> collaborations(String pid){return s.read("collaborations.json").stream().filter(x->pid.equals(String.valueOf(x.get("projectId")))).toList();}
 public Map<String,Object> impact(String actor,String role,String pid,Map<String,Object> req){Map<String,Object> x=new LinkedHashMap<>(req);x.put("id",ids.id("impact"));x.put("projectId",pid);x.put("verified",false);x.put("submittedAt",Instant.now().toString());s.add("impact-metrics.json",x);return x;}public List<Map<String,Object>> impacts(String pid){return s.read("impact-metrics.json").stream().filter(x->pid.equals(String.valueOf(x.get("projectId")))).toList();}public Map<String,Object> verifyImpact(String actor,String role,String id){Map<String,Object> x=s.update("impact-metrics.json",id,Map.of("verified",true,"verifiedBy",actor,"verifiedAt",Instant.now().toString()));audit.log(actor,role,"IMPACT_VERIFIED","IMPACT",id,null,x);return x;}
 public Map<String,Object> fieldTest(String actor,String pid,Map<String,Object> req){Map<String,Object>x=new LinkedHashMap<>(req);x.put("id",ids.id("fieldtest"));x.put("projectId",pid);x.put("submittedBy",actor);x.put("adminVerified",false);x.put("createdAt",Instant.now().toString());s.add("field-tests.json",x);return x;}public List<Map<String,Object>> fieldTests(String pid){return s.read("field-tests.json").stream().filter(x->pid.equals(String.valueOf(x.get("projectId")))).toList();}public Map<String,Object> verifyFieldTest(String actor,String role,String id){Map<String,Object>x=s.update("field-tests.json",id,Map.of("adminVerified",true,"verifiedBy",actor,"verifiedAt",Instant.now().toString()));audit.log(actor,role,"FIELD_TEST_VERIFIED","FIELD_TEST",id,null,x);return x;}
 public Map<String,Object> addFeedback(String actor,String pid,Map<String,Object> req){Map<String,Object> x=new LinkedHashMap<>(req);x.put("id",ids.id("feedback"));x.put("problemId",pid);x.put("userId",actor);x.put("createdAt",Instant.now().toString());s.add("feedback.json",x);return x;}public List<Map<String,Object>> feedback(String pid){return s.read("feedback.json").stream().filter(x->pid.equals(String.valueOf(x.get("problemId")))).toList();}
 public List<Map<String,Object>> engagement(String pid){return s.read("engagement.json").stream().filter(x->pid.equals(String.valueOf(x.get("problemId")))).toList();}
 public Map<String,Object> engage(String actor,String pid,String type,String text){
   if(s.find("problems.json",pid)==null) throw new RuntimeException("Problem not found");
   if(!Set.of("LIKE","REPOST","COMMENT","SHARE").contains(type)) throw new RuntimeException("Unsupported engagement type");
   if("COMMENT".equals(type) && (text==null || text.isBlank())) throw new RuntimeException("Comment text is required");
   Map<String,Object> e=new LinkedHashMap<>(); e.put("id",ids.id("eng")); e.put("problemId",pid); e.put("userId",actor); e.put("type",type); if(text!=null&&!text.isBlank()) e.put("text",text.trim()); e.put("createdAt",Instant.now().toString()); s.add("engagement.json",e); return e;
 }
 public Map<String,Object> engagementSummary(String pid){
   var all=engagement(pid); long likes=all.stream().filter(x->"LIKE".equals(x.get("type"))).count(); long reposts=all.stream().filter(x->"REPOST".equals(x.get("type"))).count(); long shares=all.stream().filter(x->"SHARE".equals(x.get("type"))).count(); long comments=all.stream().filter(x->"COMMENT".equals(x.get("type"))).count();
   return Map.of("likes",likes,"reposts",reposts,"shares",shares,"comments",comments);
 }
 public List<Map<String,Object>> notifications(String userId){return s.read("notifications.json").stream().filter(x->userId.equals(String.valueOf(x.get("userId")))).toList();}
 public List<Map<String,Object>> points(String userId){return s.read("civic-points.json").stream().filter(x->userId.equals(String.valueOf(x.get("userId")))).toList();}
 public List<Map<String,Object>> leaderboard(){ Map<String,Integer> totals=new HashMap<>(); for(Map<String,Object> x:s.read("civic-points.json")){ if(!Boolean.TRUE.equals(x.getOrDefault("verified",false))) continue; String uid=String.valueOf(x.get("userId")); totals.merge(uid,((Number)x.getOrDefault("points",0)).intValue(),Integer::sum); } List<Map<String,Object>> out=new ArrayList<>(); for(var e:totals.entrySet()){Map<String,Object> u=s.find("users.json",e.getKey()); out.add(Map.of("userId",e.getKey(),"name",u==null?"Citizen":u.getOrDefault("name","Citizen"),"points",e.getValue()));} out.sort((a,b)->Integer.compare(((Number)b.get("points")).intValue(),((Number)a.get("points")).intValue())); return out.stream().limit(20).toList();}
}
