import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { Activity, BarChart3, CheckCircle2, Clock3, FileCheck, FolderKanban, ShieldCheck, Users, Workflow } from 'lucide-react';
import StatCard from '../../components/common/StatCard';
import Badge from '../../components/common/Badge';
import { api } from '../../services/api';

export default function AdminWorkspace() {
  const [data,setData]=useState<any>({}); const [problems,setProblems]=useState<any[]>([]); const [users,setUsers]=useState<any[]>([]);
  const load=async()=>{const [d,p,u]=await Promise.allSettled([api.get('/admin/dashboard'),api.get('/admin/problems'),api.get('/admin/users')]);if(d.status==='fulfilled')setData(d.value.data||{});if(p.status==='fulfilled')setProblems(p.value.data||[]);if(u.status==='fulfilled')setUsers(u.value.data||[])};
  useEffect(()=>{void load()},[]);
  const queue=useMemo(()=>problems.filter(p=>['PENDING_VALIDATION','AI_ANALYZED'].includes(p.status)),[problems]);
  const routed=problems.filter(p=>['ROUTED','ACCEPTED'].includes(p.status)).length;
  return <div className="space-y-6"><header><div className="text-xs uppercase tracking-widest font-black text-jharkhand-700">ADMIN WORKSPACE</div><h1 className="text-3xl font-black mt-1">Governance control room</h1><p className="text-slate-500 mt-1">Validate AI decisions, control routing, oversee users and measure platform outcomes.</p></header>
    <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4"><StatCard label="Total problems" value={data.totalProblems||problems.length} icon={Workflow}/><StatCard label="Validation queue" value={queue.length} icon={Clock3}/><StatCard label="Routed / accepted" value={routed} icon={CheckCircle2}/><StatCard label="Active projects" value={data.activeProjects||0} icon={FolderKanban}/><StatCard label="Field tests" value={data.fieldTests||0} icon={Activity}/><StatCard label="Deployed" value={data.deployedSolutions||0} icon={ShieldCheck}/><StatCard label="Verified impact" value={data.verifiedImpact||0} icon={BarChart3}/><StatCard label="Platform users" value={users.length} icon={Users}/></div>
    <div className="grid lg:grid-cols-[1.15fr_.85fr] gap-5"><section className="card p-6"><div className="flex items-center justify-between"><div><h2 className="text-xl font-black">Human validation queue</h2><p className="text-sm text-slate-500 mt-1">Grok recommends; the Admin makes the official decision.</p></div><Link to="/admin/validation" className="btn btn-primary"><ShieldCheck size={16}/>Review queue</Link></div><div className="mt-5 space-y-3">{queue.slice(0,7).map(p=><Link to={`/problems/${p.id}`} key={p.id} className="block p-4 rounded-xl bg-slate-50 hover:bg-jharkhand-50"><div className="flex justify-between gap-3"><div><div className="font-bold">{p.title}</div><div className="text-xs text-slate-500 mt-1">{p.category||'Unclassified'} · {p.location?.district||'Jharkhand'}</div></div><Badge tone="amber">{String(p.status).replaceAll('_',' ')}</Badge></div></Link>)}{!queue.length&&<div className="py-10 text-center text-slate-400">Validation queue is clear.</div>}</div></section>
    <aside className="space-y-5"><div className="card p-6"><h2 className="font-black">Admin operations</h2><div className="grid grid-cols-2 gap-3 mt-4">{[['Validation','/admin/validation',ShieldCheck],['Analytics','/admin/analytics',BarChart3],['Users','/admin/users',Users],['Audit','/admin/audit',FileCheck],['Governance','/admin/governance',ShieldCheck],['All problems','/problems',Workflow]].map(([t,to,I]:any)=><Link to={to} key={to} className="p-4 rounded-xl bg-slate-50 hover:bg-jharkhand-50"><I size={17} className="text-jharkhand-700"/><div className="font-bold text-sm mt-2">{t}</div></Link>)}</div></div><div className="card p-6"><h2 className="font-black">Decision rule</h2><p className="text-sm leading-6 text-slate-500 mt-2">AI classification is advisory. Validation, routing approval, field-test verification and impact verification remain human-controlled.</p></div></aside></div>
  </div>;
}
