package in.jharkhand.civic.controller;
import in.jharkhand.civic.repository.JsonStore; import in.jharkhand.civic.service.AuditService; import in.jharkhand.civic.service.WorkflowService; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.security.core.Authentication; import org.springframework.web.bind.annotation.*; import java.time.Instant; import java.util.*;
@RestController @RequestMapping("/api") public class RoleActionController {private final JsonStore s;private final AuditService audit;private final WorkflowService w;public RoleActionController(JsonStore s,AuditService a,WorkflowService w){this.s=s;this.audit=a;this.w=w;}
 @PostMapping("/departments/problems/{id}/accept") @PreAuthorize("hasRole('DEPARTMENT')") Map<String,Object> depAccept(@PathVariable String id,Authentication a){return changeProblem(id,"ACCEPTED",a,"DEPARTMENT_ACCEPTED_PROBLEM");}
 @PostMapping("/departments/problems/{id}/clarify") @PreAuthorize("hasRole('DEPARTMENT')") Map<String,Object> clarify(@PathVariable String id,@RequestBody Map<String,Object> r,Authentication a){return changeProblem(id,"NEEDS_CLARIFICATION",a,"DEPARTMENT_REQUESTED_CLARIFICATION");}
 @PostMapping("/departments/problems/{id}/reject") @PreAuthorize("hasRole('DEPARTMENT')") Map<String,Object> depReject(@PathVariable String id,Authentication a){return changeProblem(id,"REJECTED",a,"DEPARTMENT_REJECTED_PROBLEM");}
 @PostMapping("/institutions/projects/{id}/accept") @PreAuthorize("hasRole('INSTITUTION')") Map<String,Object> instAccept(@PathVariable String id,Authentication a){return w.updateProject(id,Map.of("status","TEAM_FORMED"));}
 @PostMapping("/institutions/projects/{id}/reject") @PreAuthorize("hasRole('INSTITUTION')") Map<String,Object> instReject(@PathVariable String id){return w.updateProject(id,Map.of("status","REJECTED"));}
 @PostMapping("/projects/{id}/status") @PreAuthorize("hasAnyRole('ADMIN','DEPARTMENT','INSTITUTION','INDUSTRY')") Map<String,Object> projectStatus(@PathVariable String id,@RequestBody Map<String,Object> r,Authentication a){return w.updateProject(id,Map.of("status",r.get("status")));}
 private Map<String,Object> changeProblem(String id,String status,Authentication a,String action){Map<String,Object> p=s.find("problems.json",id);if(p==null)throw new RuntimeException("Problem not found");var x=s.update("problems.json",id,Map.of("status",status,"updatedAt",Instant.now().toString()));String role=a==null?"DEMO":a.getAuthorities().stream().map(xr->xr.getAuthority().replace("ROLE_","")).findFirst().orElse("DEMO"); audit.log(a==null?"user-demo":a.getName(),role,action,"PROBLEM",id,p,x);return x;}
}
