import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, Bell, Building2, Factory, Filter, GraduationCap, Landmark, PlusCircle, Search, ShieldCheck, Sparkles, Users } from 'lucide-react';
import { api } from '../services/api';
import CommunityProblemCard from '../components/problems/CommunityProblemCard';
import { useAuth, demos } from '../context/AuthContext';
import type { Role } from '../types';

const roles:{role:Role;title:string;desc:string;icon:any}[]=[
 {role:'USER',title:'Citizen',desc:'Post local problems, discuss them and follow their resolution.',icon:Users},
 {role:'ADMIN',title:'Admin',desc:'Validate AI findings, govern routing and monitor outcomes.',icon:ShieldCheck},
 {role:'DEPARTMENT',title:'Department',desc:'Own routed civic problems and move them toward resolution.',icon:Landmark},
 {role:'INSTITUTION',title:'Institution',desc:'Research, prototype, test and validate solutions.',icon:GraduationCap},
 {role:'INDUSTRY',title:'Industry',desc:'Join approved opportunities with technology, funding and deployment.',icon:Factory},
];
export default function Home(){const{user,switchRole}=useAuth();const[problems,setProblems]=useState<any[]>([]);const[q,setQ]=useState('');const[category,setCategory]=useState('ALL');useEffect(()=>{api.get('/problems').then(r=>setProblems(r.data||[])).catch(()=>{})},[]);const feed=useMemo(()=>problems.filter(p=>`${p.title} ${p.description} ${p.category} ${p.location?.district}`.toLowerCase().includes(q.toLowerCase())&&(category==='ALL'||p.category===category)),[problems,q,category]);const cats=[...new Set(problems.map(p=>p.category).filter(Boolean))];return <div className="space-y-7">
 <section className="grid lg:grid-cols-[1.2fr_.8fr] gap-5"><div className="card p-7 md:p-10 bg-white"><div className="badge bg-jharkhand-50 text-jharkhand-700"><span className="h-2 w-2 rounded-full bg-jharkhand-600 mr-2"/>Community civic network</div><h1 className="text-4xl md:text-5xl font-black tracking-tight mt-5 text-navy">See a problem.<br/><span className="text-jharkhand-700">Post it. Solve it together.</span></h1><p className="text-slate-600 text-lg leading-8 mt-5 max-w-2xl">A public community feed where citizens raise real issues, neighbours add context, and government, institutions and industry move validated problems toward measurable solutions.</p><div className="flex flex-wrap gap-3 mt-7"><Link to="/submit" className="btn btn-primary"><PlusCircle size={17}/>Post a problem</Link><a href="#community" className="btn btn-secondary">Explore community <ArrowRight size={16}/></a></div><div className="flex flex-wrap gap-5 mt-7 text-xs font-bold text-slate-500"><span>✓ Public discussion</span><span>✓ AI-assisted understanding</span><span>✓ Human validation</span></div></div><div className="card p-6 bg-[#edf8f1]"><div className="flex items-center gap-3"><div className="h-11 w-11 rounded-xl bg-white text-jharkhand-700 grid place-items-center"><Sparkles/></div><div><div className="font-black">How a post becomes impact</div><div className="text-xs text-slate-500">Transparent workflow</div></div></div><div className="mt-6 space-y-3">{['Citizen posts a problem','Community adds evidence & context','Grok structures the issue','Admin validates and routes','Department + institution solve','Field test → deployment → impact'].map((x,i)=><div key={x} className="flex gap-3 items-center"><div className="h-7 w-7 rounded-full bg-white text-jharkhand-700 grid place-items-center text-xs font-black">{i+1}</div><div className="text-sm font-semibold">{x}</div></div>)}</div></div></section>
 <section id="community" className="grid lg:grid-cols-[minmax(0,1fr)_320px] gap-5 items-start"><div><div className="flex flex-col sm:flex-row sm:items-end justify-between gap-3 mb-4"><div><div className="text-xs uppercase tracking-widest font-bold text-jharkhand-700">Community feed</div><h2 className="text-2xl font-black mt-1">Problems people are raising</h2></div><Link to="/problems" className="text-sm font-bold text-jharkhand-700">View all →</Link></div><div className="card p-3 mb-4 flex flex-col sm:flex-row gap-2"><div className="relative flex-1"><Search size={16} className="absolute left-3 top-3 text-slate-400"/><input className="input pl-9" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search community problems…"/></div><select className="input sm:w-52" value={category} onChange={e=>setCategory(e.target.value)}><option value="ALL">All categories</option>{cats.map(c=><option key={c}>{c}</option>)}</select></div><div className="space-y-4">{feed.slice(0,8).map(p=><CommunityProblemCard key={p.id} problem={p}/>)}</div></div><aside className="space-y-4"><div className="card p-5"><div className="flex items-center gap-2 font-black"><Users size={18} className="text-jharkhand-700"/>Choose your workspace</div><p className="text-xs text-slate-500 mt-2">Demo mode: switch roles without a login. Each role gets its own dashboard and permissions.</p><div className="mt-4 space-y-2">{roles.map(({role,title,desc,icon:Icon})=><button key={role} onClick={()=>switchRole(role)} className={`w-full text-left p-3 rounded-xl border transition ${user.role===role?'border-jharkhand-300 bg-jharkhand-50':'border-slate-100 hover:border-jharkhand-200'}`}><div className="flex gap-3"><div className="h-9 w-9 rounded-lg bg-white grid place-items-center text-jharkhand-700"><Icon size={17}/></div><div><div className="font-bold text-sm">{title}</div><div className="text-[11px] text-slate-500 mt-0.5">{desc}</div></div></div></button>)}</div></div><div className="card p-5"><div className="font-black flex items-center gap-2"><Bell size={17} className="text-jharkhand-700"/>Community norms</div><ul className="text-xs text-slate-500 mt-3 space-y-2 list-disc pl-4"><li>Share factual local context.</li><li>Keep comments constructive.</li><li>Report urgent safety concerns clearly.</li><li>Government decisions remain human-validated.</li></ul></div></aside></section>
 <section className="card p-6"><div className="flex items-center gap-3"><Building2 className="text-jharkhand-700"/><div><h2 className="font-black text-xl">One community, five workspaces</h2><p className="text-sm text-slate-500">The public feed stays community-first; the operational system becomes role-specific after validation.</p></div></div><div className="grid md:grid-cols-5 gap-3 mt-5">{roles.map(({role,title,icon:Icon})=><Link key={role} to={role==='USER'?'/dashboard':`/${role.toLowerCase()}`} className="bg-slate-50 hover:bg-jharkhand-50 rounded-xl p-4"><Icon size={18} className="text-jharkhand-700"/><div className="font-bold mt-3 text-sm">{title}</div><div className="text-[11px] text-slate-400 mt-1">{demos[role].name}</div></Link>)}</div></section>
 </div>}
