import { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import { api } from '../services/api';
import { CheckCircle2, Clock3, Factory, FlaskConical, MapPin, Plus, ShieldCheck, Send } from 'lucide-react';
import Badge from '../components/common/Badge';
import { useAuth } from '../context/AuthContext';

const stages = ['Research','Requirement Analysis','Design','Prototype','Internal Testing','Field Testing','Validation','Deployment','Impact Measurement'];
const roleCanEdit = (role?: string) => ['ADMIN','DEPARTMENT','INSTITUTION'].includes(role || '');

export default function ProjectDetail(){
  const { id } = useParams();
  const { user } = useAuth();
  const [p,setP]=useState<any>(); const [ms,setMs]=useState<any[]>([]); const [impact,setImpact]=useState<any[]>([]); const [tests,setTests]=useState<any[]>([]); const [collabs,setCollabs]=useState<any[]>([]);
  const [busy,setBusy]=useState(false); const [message,setMessage]=useState(''); const [solutionFiles,setSolutionFiles]=useState<File[]>([]);
  const [form,setForm]=useState({name:'',description:'',startDate:'',endDate:'',status:'NOT_STARTED',progress:'0'});
  const [test,setTest]=useState({testLocation:'',date:'',participants:'',testObjectives:'',results:'',issues:'',feedback:'',successRate:'0',evidence:[] as File[]});
  const [imp,setImp]=useState<Record<string,string>>({peopleBenefited:'',costReduction:'',timeSaved:'',waterSaved:'',energySaved:'',wasteReduced:'',accessibilityImprovement:'',serviceImprovement:'',responseTimeImprovement:'',citizenSatisfaction:''});

  const load=()=>{ if(!id)return; Promise.all([api.get(`/projects/${id}`),api.get(`/projects/${id}/milestones`),api.get(`/projects/${id}/impact`),api.get(`/projects/${id}/field-tests`),api.get(`/projects/${id}/collaborations`)]).then(([a,b,c,d,e])=>{setP(a.data);setMs(b.data);setImpact(c.data);setTests(d.data);setCollabs(e.data);}); };
  useEffect(load,[id]);

  const addMilestone=async()=>{if(!id||!form.name)return;setBusy(true);try{await api.post(`/projects/${id}/milestones`,{...form,progress:Number(form.progress)});setForm({name:'',description:'',startDate:'',endDate:'',status:'NOT_STARTED',progress:'0'});load();}finally{setBusy(false)}};
  const addTest=async()=>{if(!id)return;setBusy(true);try{const fd=new FormData();fd.append('payload',JSON.stringify({...test,evidence:[],successRate:Number(test.successRate)}));test.evidence.forEach(f=>fd.append('files',f));await api.post(`/projects/${id}/field-tests/upload`,fd,{headers:{'Content-Type':'multipart/form-data'}});setMessage('Field test submitted for admin verification.');setTest(t=>({...t,testLocation:'',results:'',issues:'',feedback:''}));load();}finally{setBusy(false)}};
  const addImpact=async()=>{if(!id)return;setBusy(true);try{await api.post(`/projects/${id}/impact`,Object.fromEntries(Object.entries(imp).map(([k,v])=>[k,Number(v)||v])));setMessage('Impact submitted for verification.');load();}finally{setBusy(false)}};
  const acceptProject=async()=>{if(!id)return;await api.post(`/institutions/projects/${id}/accept`);setMessage('Project accepted and team formation started.');load();}; const rejectProject=async()=>{if(!id)return;await api.post(`/institutions/projects/${id}/reject`);setMessage('Project invitation rejected.');load();};
  const uploadSolutionFiles=async()=>{if(!id||!solutionFiles.length)return;const fd=new FormData();solutionFiles.forEach(f=>fd.append('files',f));await api.post(`/projects/${id}/files`,fd,{headers:{'Content-Type':'multipart/form-data'}});setMessage('Research/prototype files uploaded.');setSolutionFiles([]);load();};
  const invite=async()=>{if(!id)return;await api.post(`/projects/${id}/industry/invite`,{partnershipType:'Technology / Testing',contribution:'Support requested',status:'SENT'});setMessage('Industry collaboration request created.');load();};

  if(!p)return <div className="py-20 text-center text-slate-500">Loading project…</div>;
  return <div className="space-y-5">
    <div className="card p-7"><div className="flex flex-col md:flex-row justify-between gap-5"><div><Badge tone="blue">{p.status?.replaceAll('_',' ')}</Badge><h1 className="text-3xl font-black mt-3">{p.title}</h1><p className="text-slate-500 mt-2 max-w-3xl">{p.scope}</p></div><div className="text-right"><div className="text-xs text-slate-400">Budget</div><div className="text-2xl font-black">₹{Number(p.budget||0).toLocaleString('en-IN')}</div></div></div></div>

    {user?.role==='INSTITUTION'&&<div className="card p-5"><div className="font-bold">Institution project decision</div><div className="text-sm text-slate-500 mt-1">Accept the invitation to form a team and begin research, or reject it.</div><div className="flex gap-2 mt-3"><button onClick={acceptProject} className="btn btn-primary">Accept project</button><button onClick={rejectProject} className="btn btn-danger">Reject project</button></div></div>}

    <div className="card p-6"><div className="flex items-center justify-between"><h2 className="font-black text-xl">Project lifecycle</h2><span className="text-xs text-slate-400">9 stages</span></div><div className="grid md:grid-cols-3 gap-3 mt-5">{stages.map((x,i)=>{const m=ms.find(z=>z.name===x);return <div key={x} className={`rounded-xl p-4 border ${m?.status==='COMPLETED'?'border-jharkhand-200 bg-jharkhand-50':'border-slate-200 bg-slate-50'}`}><div className="flex items-center gap-2"><div className="h-8 w-8 rounded-lg bg-white grid place-items-center text-jharkhand-700">{m?.status==='COMPLETED'?<CheckCircle2 size={16}/>:<Clock3 size={16}/>}</div><div className="font-bold text-sm">{i+1}. {x}</div></div><div className="text-xs text-slate-500 mt-3">{m?.progress||0}% • {m?.status?.replaceAll('_',' ')||'NOT_STARTED'}</div><div className="h-1.5 bg-slate-200 rounded-full mt-2 overflow-hidden"><div className="h-full bg-jharkhand-500" style={{width:`${m?.progress||0}%`}}/></div></div>})}</div></div>

    <div className="grid lg:grid-cols-2 gap-5">
      <div className="card p-6"><div className="flex justify-between items-center"><h2 className="font-black text-xl">Milestones</h2>{roleCanEdit(user?.role)&&<Plus size={18}/>}</div><div className="mt-4 space-y-3">{ms.map(m=><div className="p-4 rounded-xl bg-slate-50" key={m.id}><div className="flex justify-between gap-3"><div><div className="font-bold">{m.name}</div><div className="text-xs text-slate-400 mt-1">{m.startDate||'—'} → {m.endDate||'—'}</div></div><b>{m.progress}%</b></div></div>)}</div>{roleCanEdit(user?.role)&&<div className="mt-5 border-t pt-5 grid md:grid-cols-2 gap-3"><input className="input" placeholder="Milestone name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input className="input" placeholder="Description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><input className="input" type="date" value={form.startDate} onChange={e=>setForm({...form,startDate:e.target.value})}/><input className="input" type="date" value={form.endDate} onChange={e=>setForm({...form,endDate:e.target.value})}/><select className="input" value={form.status} onChange={e=>setForm({...form,status:e.target.value})}>{['NOT_STARTED','IN_PROGRESS','COMPLETED','BLOCKED'].map(x=><option key={x}>{x}</option>)}</select><input className="input" type="number" min="0" max="100" value={form.progress} onChange={e=>setForm({...form,progress:e.target.value})}/><button onClick={addMilestone} disabled={busy} className="btn btn-primary md:col-span-2">Add milestone</button></div>}</div>

      <div className="space-y-5"><div className="card p-6"><div className="flex items-center gap-3"><Factory className="text-jharkhand-700"/><div><h2 className="font-black">Industry collaboration</h2><p className="text-xs text-slate-400">Available only after initial routing.</p></div></div>{['DEPARTMENT','INSTITUTION','ADMIN'].includes(user?.role||'')&&<button onClick={invite} className="btn btn-secondary mt-4"><Send size={15}/>Request industry collaboration</button>}<div className="mt-4 space-y-2">{collabs.map(c=><div className="p-3 rounded-xl bg-slate-50 text-sm" key={c.id}><b>{c.partnershipType||'Collaboration'}</b><span className="text-slate-400 ml-2">{c.status}</span></div>)}</div></div>

      <div className="card p-6"><h2 className="font-black">Impact tracking</h2><p className="text-sm text-slate-500 mt-1">Admin/Department verification is required before impact becomes verified.</p><div className="grid sm:grid-cols-2 gap-3 mt-4">{[['peopleBenefited','People benefited'],['costReduction','Cost reduction'],['timeSaved','Time saved'],['waterSaved','Water saved'],['energySaved','Energy saved'],['wasteReduced','Waste reduced'],['accessibilityImprovement','Accessibility improvement'],['serviceImprovement','Service improvement'],['responseTimeImprovement','Response time improvement'],['citizenSatisfaction','Citizen satisfaction']].map(([k,l])=><label className="text-xs font-bold" key={k}>{l}<input className="input mt-1" value={imp[k]} onChange={e=>setImp({...imp,[k]:e.target.value})}/></label>)}</div>{roleCanEdit(user?.role)&&<button onClick={addImpact} className="btn btn-primary mt-4">Submit impact</button>}<div className="mt-4 space-y-2">{impact.map(x=><div key={x.id} className="p-3 rounded-xl bg-slate-50 text-sm"><b>{x.peopleBenefited||0} benefited</b><span className="text-slate-400 ml-2">{x.verified?'Verified':'Pending verification'}</span></div>)}</div></div></div>
    </div>

    <div className="card p-6"><h2 className="font-black">Research & prototype files</h2><p className="text-sm text-slate-500 mt-1">Institutions can upload research notes, prototype information and final solution evidence.</p>{roleCanEdit(user?.role)&&<div className="mt-4 flex flex-col md:flex-row gap-3"><input type="file" multiple className="input" onChange={e=>setSolutionFiles(Array.from(e.target.files||[]))}/><button onClick={uploadSolutionFiles} className="btn btn-primary">Upload files</button></div>}<div className="mt-4 text-sm text-slate-500">{(p.attachments||[]).length ? (p.attachments.length+" file(s) attached to this project.") : "No project files uploaded yet."}</div></div>

    <div className="card p-6"><div className="flex items-center gap-3"><FlaskConical className="text-jharkhand-700"/><div><h2 className="font-black">Field testing</h2><p className="text-xs text-slate-400">Capture evidence, results and success rate.</p></div></div>{roleCanEdit(user?.role)&&<div className="grid md:grid-cols-2 gap-3 mt-5"><input className="input" placeholder="Test location" value={test.testLocation} onChange={e=>setTest({...test,testLocation:e.target.value})}/><input className="input" type="date" value={test.date} onChange={e=>setTest({...test,date:e.target.value})}/><input className="input" placeholder="Participants" value={test.participants} onChange={e=>setTest({...test,participants:e.target.value})}/><input className="input" placeholder="Success rate %" value={test.successRate} onChange={e=>setTest({...test,successRate:e.target.value})}/><textarea className="input md:col-span-2" placeholder="Test objectives" value={test.testObjectives} onChange={e=>setTest({...test,testObjectives:e.target.value})}/><textarea className="input" placeholder="Results" value={test.results} onChange={e=>setTest({...test,results:e.target.value})}/><textarea className="input" placeholder="Issues" value={test.issues} onChange={e=>setTest({...test,issues:e.target.value})}/><textarea className="input md:col-span-2" placeholder="Feedback" value={test.feedback} onChange={e=>setTest({...test,feedback:e.target.value})}/><input className="md:col-span-2" type="file" multiple onChange={e=>setTest({...test,evidence:Array.from(e.target.files||[])})}/><button onClick={addTest} disabled={busy} className="btn btn-primary md:col-span-2"><MapPin size={15}/>Submit field test</button></div>}{tests.map(x=><div key={x.id} className="mt-3 p-4 rounded-xl bg-slate-50 text-sm"><b>{x.testLocation}</b><div className="text-slate-500 mt-1">Success: {x.successRate||0}% • Admin verified: {x.adminVerified?'Yes':'Pending'}</div></div>)}{message&&<div className="text-sm text-jharkhand-700 mt-3"><ShieldCheck size={14} className="inline mr-1"/>{message}</div>}</div>
  </div>;
}
