import { Routes, Route, Navigate } from 'react-router-dom';
import type { ReactNode } from 'react';
import Shell from './components/common/Shell';
import RoleGate from './components/common/RoleGate';
import Home from './pages/Home';  import SubmitProblem from './pages/SubmitProblem'; import Problems from './pages/Problems'; import ProblemDetail from './pages/ProblemDetail'; import Projects from './pages/Projects'; import ProjectDetail from './pages/ProjectDetail'; import Institutions from './pages/Institutions'; import Departments from './pages/Departments'; import Notifications from './pages/Notifications'; import IndustryOpportunities from './pages/IndustryOpportunities'; import ProjectCreate from './pages/ProjectCreate';
import Validation from './pages/admin/Validation'; import Analytics from './pages/admin/Analytics'; import Users from './pages/admin/Users'; import Audit from './pages/admin/Audit'; import Governance from './pages/admin/Governance';
import CitizenWorkspace from './pages/roles/CitizenWorkspace';
import AdminWorkspace from './pages/roles/AdminWorkspace'; import DepartmentWorkspace from './pages/roles/DepartmentWorkspace'; import InstitutionWorkspace from './pages/roles/InstitutionWorkspace'; import IndustryWorkspace from './pages/roles/IndustryWorkspace';
const wrap=(x:ReactNode)=><Shell>{x}</Shell>;
export default function App(){return <Routes>
<Route path="/" element={wrap(<Home/>)} /><Route path="/dashboard" element={wrap(<RoleGate roles={['USER']}><CitizenWorkspace/></RoleGate>)} /><Route path="/citizen" element={wrap(<RoleGate roles={['USER']}><CitizenWorkspace/></RoleGate>)} /><Route path="/submit" element={wrap(<RoleGate roles={['USER']}><SubmitProblem/></RoleGate>)} /><Route path="/problems" element={wrap(<Problems/>)} /><Route path="/problems/:id" element={wrap(<ProblemDetail/>)} /><Route path="/projects" element={wrap(<Projects/>)} /><Route path="/projects/new" element={wrap(<RoleGate roles={['ADMIN','DEPARTMENT']}><ProjectCreate/></RoleGate>)} /><Route path="/projects/:id" element={wrap(<ProjectDetail/>)} /><Route path="/institutions" element={wrap(<Institutions/>)} /><Route path="/departments" element={wrap(<Departments/>)} /><Route path="/notifications" element={wrap(<Notifications/>)} />
<Route path="/admin" element={wrap(<RoleGate roles={['ADMIN']}><AdminWorkspace/></RoleGate>)} /><Route path="/admin/dashboard" element={wrap(<RoleGate roles={['ADMIN']}><AdminWorkspace/></RoleGate>)} /><Route path="/admin/validation" element={wrap(<RoleGate roles={['ADMIN']}><Validation/></RoleGate>)} /><Route path="/admin/analytics" element={wrap(<RoleGate roles={['ADMIN']}><Analytics/></RoleGate>)} /><Route path="/admin/users" element={wrap(<RoleGate roles={['ADMIN']}><Users/></RoleGate>)} /><Route path="/admin/audit" element={wrap(<RoleGate roles={['ADMIN']}><Audit/></RoleGate>)} /><Route path="/admin/governance" element={wrap(<RoleGate roles={['ADMIN']}><Governance/></RoleGate>)} />
<Route path="/department" element={wrap(<RoleGate roles={['DEPARTMENT']}><DepartmentWorkspace/></RoleGate>)} /><Route path="/department/dashboard" element={wrap(<RoleGate roles={['DEPARTMENT']}><DepartmentWorkspace/></RoleGate>)} />
<Route path="/institution" element={wrap(<RoleGate roles={['INSTITUTION']}><InstitutionWorkspace/></RoleGate>)} /><Route path="/institution/dashboard" element={wrap(<RoleGate roles={['INSTITUTION']}><InstitutionWorkspace/></RoleGate>)} />
<Route path="/industry" element={wrap(<RoleGate roles={['INDUSTRY']}><IndustryWorkspace/></RoleGate>)} /><Route path="/industry/dashboard" element={wrap(<RoleGate roles={['INDUSTRY']}><IndustryWorkspace/></RoleGate>)} /><Route path="/industry/opportunities" element={wrap(<RoleGate roles={['INDUSTRY']}><IndustryOpportunities/></RoleGate>)} />
<Route path="*" element={<Navigate to="/" replace/>}/></Routes>}
